name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: Checkmarx/ast-github-action@2.0.3
        with:
          project_name: ${{ github.repository }}
          cx_tenant: ps_tenant
          base_uri: https://eu.ast.checkmarx.net 
          cx_client_id: ${{ secrets.CLIENT_ID }}
          cx_client_secret: ${{ secrets.SECRET }}
          branch: ${{ github.ref }}
          additional_params: --tags test1, test2 --scan-types sast,kics --file-filter !readme --report-format sarif --output-name results 
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with: 
          sarif_file: results.sarif
