name: Checkmarx AST Scan
on: {push, pull_request}
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkmarx AST Github Action
      uses: Checkmarx/ast-github-action@2.0.3
      with:
        base_uri: https://eu.ast.checkmarx.net
        cx_tenant: ps_tenant
        cx_client_id: ${{ secrets.CLIENT_ID }}
        cx_client_secret: ${{ secrets.CLIENT_SECRET }}
        project_name: ${{ github.repository }}
        branch: ${{ github.ref }}
  
